try{
    
    console.log(fff)
}
    catch(error){
        console.log(error)
    }
