// try {
//     // Some code that might throw an error
//     const result = doSomething();
//     console.log(result);
//   } catch (error) {
//     // Handle the error
//     console.error('An error occurred:', error);
//   }
  


